[package]
name = "ru_annoy"
version = "0.1.0"
authors = ["kis3tar"]
license = "MIT"
repository = "https://github.com/kis3tar/RuAnnoy"
description = """
A rust implementation of annoy(https://github.com/spotify/annoy) (Index serving only). Providing C api as well
"""

[dependencies]
libc = "0.2"
memmap = "0.6.2"


[lib]
crate-type = ["lib", "cdylib"]
